influxdata/influxdb-client-js

src/wrappers/tasks.ts

Update tasks to include the api call for getting runs by taskID

Update client for tasks with returning of runs by taskID

---

package-lock.json
src/api/api.ts
src/index.ts
src/wrappers/variables.ts

This PR will add API function to get, create, and delete template variables.

Add get, create, and delete functions for template variables

---

src/api/api.ts

This PR adds the `orgID` property to the Macro type to match the implementation.

Add orgID property to Macro type

---

src/wrappers/buckets.ts
src/wrappers/tasks.ts

This commit removed unused imports from Buckets and Tasks

Removed unused Organization imports

---

src/api/api.ts
src/wrappers/tasks.ts
src/wrappers/variables.ts

This PR renames all occurrences of "Macro" to "Variable"

Rename Macros to Variables

---

src/api/api.ts
src/wrappers/variables.ts

This PR adds the routes to get  and update a single variable by its ID.

Add get/update variable by ID routes

---

src/wrappers/organizations.ts

For https://github.com/influxdata/influxdb/issues/11980

Update orgs wrapper to include owners post api call

---

src/wrappers/labels.ts
src/wrappers/tasks.ts
src/wrappers/templates.ts

Add create from template function and createByOrgID function to tasks

Add create from template function to tasks

---

package.json

update(package.version): version 0.2.27

---

src/types/index.ts
src/wrappers/telegrafConfigs.ts

__Briefly Describe Your Changes__
These changes ensure defaults label type of `ILabel` for the `Telegraf` response

fix(wrappers/telegrafs): ensure labels for telegrafs

---

package-lock.json
package.json
src/api/api.ts
src/wrappers/labels.ts

cause we need to update dat label name!

feat(labels): update label name

---

src/types/index.ts
src/wrappers/templates.ts

Add label type defaults to DocumentListEntry and call it TemplateSummary.

Add TemplateSummary type, and defaults. 

---

src/utils/sagas.ts
src/wrappers/labels.ts

- Implement for labels createAll

Introduce sagas for transactions

---

src/wrappers/tasks.ts

Part 1 of https://github.com/influxdata/influxdb/issues/12889
Remove wrapper for `tasks.createFromTemplate` and prefer to manage template API calls from the UI.

rm(wrappers/tasks.createFromTemplate): prefer wrapping calls in UI

---

src/wrappers/templates.ts

Updating templates wrapper to have a function for cloning a template

Update templates wrapper for cloning a template

---

src/wrappers/dashboards.ts

Templating methods were moved to frontend, removing them here.

Remove templating methods from dashboards

---

package-lock.json
src/wrappers/templates.ts

This PR adds a wrapper to for updating a Template to `templates.ts`
It also updates the version in the package-lock.json file.

Add wrapper for updating a Template

---

src/wrappers/users.ts

- fix getAll to follow standard format

Add get to users wrapper

---

src/wrappers/buckets.ts

in buckets wrapper, add optional orgID param to getAll 
Call create function with CreateBucket type

Add createBucket type and optional orgID to getAll

---

src/wrappers/variables.ts

Add getAll with optional orgID param
variable type already requires orgID and name

Add getAll with optional orgID to variables

---

src/api/api.ts
src/wrappers/templates.ts

and incorporate swagger changes that add orgID field to templates getAll

add orgID to templates getAll

---

dist/wrappers/dashboards.d.ts
dist/wrappers/dashboards.js
src/wrappers/dashboards.ts

chore(dashboards): clone takes an orgID

---

dist/api/api.d.ts
dist/api/api.js
dist/types/index.d.ts
dist/wrappers/templates.d.ts
dist/wrappers/templates.js
src/api/api.ts
src/wrappers/templates.ts

Closes #94 
__Briefly Describe Yo CH-ch-changes__
Generates the client types and update the templates wrapper to implement `add` and `remove` for labels.

update(wrappers/template): add/remove labels from templates

---

dist/api/api.d.ts
dist/api/api.js
dist/wrappers/buckets.d.ts
dist/wrappers/labels.js
dist/wrappers/scrapers.js
dist/wrappers/tasks.js
dist/wrappers/telegrafConfigs.js
src/api/api.ts
src/wrappers/buckets.ts
src/wrappers/labels.ts
src/wrappers/scrapers.ts
src/wrappers/tasks.ts
src/wrappers/telegrafConfigs.ts

regenerate api due to swagger changes

---

dist/wrappers/tasks.js
src/wrappers/tasks.ts

* fix(tasks): remove unneeded keys from task update
* chore: update dist

fix(tasks): remove unneeded keys from task update (#118)

---

dist/wrappers/templates.js
src/wrappers/templates.ts

Connect https://github.com/influxdata/influxdb/issues/14086

Fix cloning templates with labels

---

dist/wrappers/tasks.d.ts
dist/wrappers/tasks.js
src/wrappers/tasks.ts

Have to update the task's create function to have token with the post api call

Update tasks wrapper's create to include token in post api

---

src/api/api.ts

Reverts influxdata/influxdb-client-js#142

Revert "Add bucket type to js client api"

---

CHANGELOG.md
packages/core/src/impl/browser/FetchTransport.ts

Fixes #160 
https://github.com/influxdata/influxdb/pull/17525

fix: Disabled using credentials for CORS

---

CHANGELOG.md
README.md
examples/README.md
examples/influxdb-1.8.ts

Updated README.md with info about InfluxDB 1.8
https://github.com/influxdata/influxdb-client-js/blob/e918f17db4638ab4d0e62ab6bcd5ebf254a5dcba/README.md

docs: Clarify how to use a client with InfluxDB 1.8

---

CHANGELOG.md
packages/core/src/InfluxDB.ts
packages/core/test/unit/Influxdb.test.ts

Releated-to https://github.com/influxdata/influxdb-client-python/issues/87

feat: remove trailing slash from connection URL

---

CHANGELOG.md
examples/write.js
packages/core/src/WriteApi.ts

Fixes #192 
* Add comments into write.js example
* Enhance documentation of WriteAPI

feat(docs): explain writeApi buffering in the example and api docs

---

CHANGELOG.md
packages/apis/resources/operations.json
packages/apis/resources/swagger.yml
packages/apis/src/generated/BucketsAPI.ts
packages/apis/src/generated/DashboardsAPI.ts
packages/apis/src/generated/OrgsAPI.ts
packages/apis/src/generated/PackagesAPI.ts
packages/apis/src/generated/UsersAPI.ts
packages/apis/src/generated/types.ts

Updates APIs from swagger after merging https://github.com/influxdata/influxdb/commit/a4ce371c197cab206695a89f39b3185ffcd5dfb6

feat(apis): regenerate API from the latest swagger

---

examples/.eslintrc.json
examples/README.md
examples/createBucket.js

Adds createBucket example. See #211 for details.

feat(examples): add createBucket.js example

---

CHANGELOG.md
packages/core/src/query/flux.ts

Fixes #217 
Support arrays in the `flux` tagged template.

feat(core/flux): sanitize arrays in parameterized flux queries

---

README.md
examples/.gitignore
examples/health.js
examples/influxdb-1.8.ts

This PR simplifies the main README.md and provides more information of how to get started with this client.

docs: improve main readme

---

.circleci/config.yml
CHANGELOG.md
Makefile
package.json
packages/core/src/index.ts
scripts/enhance-doc-index-md.js

- adjust CI tests to validate that documentation can be generated without errors
- update release instructions to publish API documentation

docs: include doc generation into CI and release process

---

CHANGELOG.md
packages/core/src/InfluxDB.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/Influxdb.test.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #249, implementation follows the proposal therein.

feat(core): simplify precision for WriteApi retrieval

---

Makefile
README.md

This PR improves the main readme by (re)moving parts that are not required therein + few other doc things repaired.

chore: improve main readme

---

README.md
packages/apis/generator/logger.ts
packages/core/src/impl/retryStrategy.ts
packages/core/src/query/flux.ts

This PR adds LGTM project badge and fixes a few LGTM warnings.

chore: add lgtm project badge

---

CHANGELOG.md
examples/package.json
examples/scripts/monitor.js
examples/scripts/server.js

This PR shows how to monitor `node.js` application. It measures cpu/memory/resource usage of the node process and also HTTP response time of the example express HTTP server.

feat(examples): add example node.js application monitoring

---

CHANGELOG.md
examples/query.deno.ts

The latest version of the client is now used in query.deno.ts

fix(examples): Use the latest client in query.deno.ts

---

CHANGELOG.md
packages/apis/DEVELOPMENT.md
packages/apis/resources/swagger.yml
packages/apis/src/generated/types.ts

This PR updates generated APIs from swagger as of 2021-02-10.

feat(apis): update APIs from swagger

---

packages/core/test/util.ts

chore(tests): prefer-rest-params

---

CHANGELOG.md
packages/apis/resources/swagger.yml
packages/apis/src/generated/types.ts

feat(apis): update APIs from swagger as of 2021-03-18

---

CHANGELOG.md
packages/core/src/query/flux.ts
packages/core/test/unit/query/flux.test.ts

 fix(core): support negative numbers in flux tagged template

---

packages/giraffe/package.json

chore(giraffe): move dependency to dev

---

CHANGELOG.md
packages/core/src/Point.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #323
* Point timestamp better documents all options of how a timestamp can be set
* all documented timestamp types are tested

feat(core): explain Point timestamp

---

CHANGELOG.md
packages/apis/resources/operations.json
packages/apis/resources/swagger.yml
packages/apis/src/generated/AuthorizationsAPI.ts
packages/apis/src/generated/types.ts

feat(apis): regenerate APIs from swagger 2021-04-22

---

examples/index.html
packages/core/src/Point.ts

Closes #352
Doc improved herein.

chore(doc): improve doc with tag name/value requirements

---

CHANGELOG.md
README.md
examples/README.md
examples/env_browser.js
examples/index.html
packages/core-browser/README.md

docs: clarify READMEs and example code comments:
- expand comments and descriptions,
- clarify differences among provided client distributions,
- explain client distribution used in browser example.

docs: clarify readme and comments

---

CHANGELOG.md
README.md
packages/core/src/options.ts

This PR enhances documentation with pointers that help setting up a proxy in communication with InfluxDB.

chore(docs): document how to setup proxy

---

CHANGELOG.md
README.md
examples/README.md
examples/delete.ts

Fixes #389 
- adds `delete.ts` example
- improves top-level documentation to signalize that there is also a delete operation is 

feat: add delete.ts example

---

README.md

This PR adds a doc link that shows how to reuse connections in node.js

chore: document connection reuse in node.js

---

examples/index.html

This PR fixes imports in the browser example.

fix(examples): fix imports in browser example

---

CHANGELOG.md
package.json
yarn.lock

This PR upgrades `lerna` to version 4

chore: upgrade lerna

---

README.md

This PR reacts to #437 and improves the docs to make sure that also `Ionic` requires a browser distribution. 

chore: describe installation for  Ionic

---

README.md
packages/apis/src/custom/FluxScriptInvocationAPI.ts

This PR references invokable scripts in the main readme

chore: add invokable scripts to main readme

---

packages/core/test/unit/WriteApi.test.ts

This PR repairs a flickering writeApi test

fix(core): repair flickering test

---

packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

This PR aims to fix a test that randomly fails in https://app.circleci.com/pipelines/github/influxdata/influxdb-client-js/1343/workflows/ecc2de31-777a-433d-9a04-ed9a7872e2b1/jobs/2916/tests

chore(core): repair flickering test

---

examples/writeAdvanced.mjs

Fixes #640
Enable `keepAlive` property to clarify correct settings.

fix(docs): enable keep alive

---

package.json
yarn.lock

Due to failures when running yarn run test, this updates all the deps.
fixes: #654

fix: run yarn update
