influxdata/influxdb-client-js

src/api/api.ts
src/wrappers/buckets.ts
src/wrappers/tasks.ts
src/wrappers/variables.ts

This PR fixes the Macro type to match the implementation. A `value` property is added to the `QueryMacroProperties` object type, and the `queryType` property is renamed to `language`.
It also changes the parameters for buckets and tasks to use the organization name string rather than 
the entire organization object.

Change org to orgName and fix macro type

---

src/wrappers/variables.ts

This PR adds a function, `getAll` to fetch all variables from all organizations.

Add function to get all variables from all orgs

---

src/api/api.ts

The result of running `npm run generate`. This to get the `description` field added to the `TelegrafRequest` typing.

Regenerate client

---

src/wrappers/dashboards.ts

Closes #33 
Fixes an issue where the return type for the dashboards wrappers did not always use the `IDashboard` interface.

fix(wrappers/dash): return IDashaboard in dashboard wrappers

---

src/types/index.ts
src/wrappers/dashboards.ts
src/wrappers/tasks.ts

When creating a dashboard or task from a template, their labels should only get created if they dont already exist.
Additionally, addLabel, addLabels, and removeLabel in Tasks wrapper should take the label id rather than the entire label itself like in dashboards.

Fix duplicating labels

---

src/wrappers/tasks.ts

Make the removeLabels arguments match addLabels, addLabel, and removeLabel for the task wrapper

Update tasks removeLabels to take labelIDs instead of labels array

---

src/types/index.ts
src/wrappers/dashboards.ts

labels are string array not ILabel Array, get all has defaults applied and returns IDashboard[]

Labels to string and fix dash type

---

package.json
src/api/api.ts
src/types/index.ts
src/wrappers/templates.ts

Closes: https://github.com/influxdata/influxdb2-js/issues/38
- converted parameters of Document schema that are guaranteed to required 
(in https://github.com/influxdata/influxdb/pull/12637#event-2204931341)
- ITemplateBase extends Document, and specific templates Like IDashboardTemplate extend ITemplateBase, ITemplate is the union of the specific templates. 
- Convert Document types returned from API to ITemplate by applying defaults to optional params.

Derive template types from Document swagger definition

---

src/api/api.ts
src/types/index.ts
src/wrappers/templates.ts

Turns out labels are not guaranteed on documents, adjusted swagger back, and added defaults in a way that doesn't require labels to work.

Add guaranteed labels parameter to templates

---

src/wrappers/dashboards.ts
src/wrappers/telegrafConfigs.ts

Telegraf and dashboard wrappers had removeLabel which took a Label object. Updated these wrappers to have a function that take an array of Label and remove multiple.

Update telegraf and dashboard labels to remove multiple

---

src/types/index.ts
src/wrappers/variables.ts

Closes #81 
__Briefly Describe Your Changes__
The client returned variables that were potentially undefined and did not check/apply defaults to each resource's label. This is important for ensuring `variable.labels[].properties` is not `any` and  has both `color: string` and `description?: string`.
Note: this is becoming a pain to catch and update in the client. We may want to consider some alternative/easier way of checking this for labeled resources.

fix(wrapper/variable.labels): ensure defaults and labels

---

src/types/index.ts

Closes #79
__Briefly Describe Your Changes__
The `ITemplateBase` allows for labels to be optional but the client was doing the work to add the defaults and ensure they exist. This change requires labels. Tried changing this in the ui locally and didn't get any linting/testing errors.

fix(wrappers/template.labels): require labels array

---

src/wrappers/variables.ts

The `variables.getAll` returns type `Variable[]` instead of `IVariable` this changes fixes that to make it consistent with other methods.

fix(wrappers/vars.getall): return IVar array

---

dist/types/index.d.ts
src/types/index.ts

closes #92 
__Briefly describe your changes__
Adds the template variable type to `ITemplate` so we can handle importing variables retrieved using `templates.get`. This will resolve variable template type errors in ui for `createResourceFromTemplate` in the ui.

fix(types/template): add variable template

---

src/index.ts
src/types/alerts.ts

Threshold and Check and Notification Rule Types were not distinguishable, extended to make them distinguishable.

Extend alert types to more distinguishable types.

---

CHANGELOG.md
package.json
yarn.lock

- security update of minimist: [ESLint dependencies are vulnerable (ReDoS and Prototype Pollution)](https://github.com/advisories/GHSA-7fhm-mqm4-2wp7)
- removed useless `generate-changelog`

fix(security): security update of minimist

---

Makefile

packages/core/src/impl/version.ts must be changed before running the build so that the new VERSION is built into distributions

chore: repair Makefile to include version

---

.circleci/config.yml
.circleci/deploy-nightly-version.sh
.circleci/setup-npmjs.sh
CHANGELOG.md
Makefile
lerna.json

Fixes #164
The CircleCI publish prerelease packages. Package versions looks like:
```
Found 2 packages to publish:
- @influxdata/influxdb-client-apis => 1.2.0-alpha.6+a9851da
- @influxdata/influxdb-client => 1.2.0-alpha.6+a9851da
```

chore: deploy prerelease packages by CircleCI

---

CHANGELOG.md
packages/core/src/Point.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/src/util/currentTime.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/util/currentTime.test.ts

Fixes #171 
Currently, when a Point is written via the WriteAPI, it can include timestamp as a string. A non-string value will silently generate the time stamp on the client. This is not handy from a user perspective, it should be possible to also set a number or Date.

feat: allow to set Point's timestamp using Date or number

---

packages/core/package.json
yarn.lock

The `typedoc v0.17.6` is without dependency to `jquery`.
- https://github.com/advisories/GHSA-jpcq-cgw6-v4j6
- https://github.com/advisories/GHSA-gxr4-xjj5-5px2

chore(dependency): updated typedoc to avoid security alerts

---

CHANGELOG.md
packages/core/src/QueryApi.ts
packages/core/src/impl/QueryApiImpl.ts
packages/core/src/query/FluxTableMetaData.ts
packages/core/test/unit/QueryApi.test.ts

Allow setting the time that should be reported as "now" in the query.

feat(query): add now to query options

---

CHANGELOG.md
packages/core/src/InfluxDB.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #184 
Adds optional writeOptions to getWriteApi
```js
getWriteApi(
org: string,
bucket: string,
precision: WritePrecision = WritePrecision.ns,
writeOptions?: Partial<WriteOptions>
): WriteApi {
```

feat(core): allow to create write API with custom writeOptions

---

examples/index.html
examples/write.js
packages/core/src/Point.ts

Fixes #188
Show how to use point timestamp to write.js, change write examples to print points as protocol lines.

fix(example): add timestamp to write example

---

CHANGELOG.md
packages/core/src/QueryApi.ts

Fixes #195
This PR removes support for influxql queries in the query API, there are multiple reasons for doing this:
* the state of support of influxql queries in InfluxDB 2.0 is unknown and not documented
* the server returns json data to influxql query, such data is not parseable by this client that expect CSV data as the only option explained by the docs
* even 1.x server does not support influxql in 2.0 compatibility API

fix(core/query): remove influxql support #195

---

CHANGELOG.md
examples/query.ts
packages/core/src/QueryApi.ts
packages/core/src/impl/QueryApiImpl.ts
packages/core/test/unit/QueryApi.test.ts

There are use cases in which the users want to receive all the query results in a Promise, knowing that the size of the data is not that big. It can be already achieved on top of the existing query API, but it would be better to provide such utility functions directly in the query API + document a warning that the new `collect*` methods store all the streamed query results into memory.
* add `collectLines` to QueryApi
* add `collectRows` to QueryApi
* enhance query example with collectRows

feat(core/query): add collectRows and collectLines to query API

---

packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #197
The following property was added to `writeOptions`, so it is now possible to know/observe/react upon writing failures in a custom way.
```
/**
* writeFailed is called to inform about write error
* @param source the instance of the API that failed
* @param error write error
* @param lines failed lines
* @param attempts a number of failed attempts to write the lines
* @return a Promise to force the API to not retry again and use the promise as a result of the flush operation,
* void/undefined to continue with default retry mechanism   
*/
writeFailed?: (
source: WriteApi,
error: Error,
lines: Array<string>,
attempts: number
) => boolean | void
```

feat(core/write): allow to supply listener for write failures

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts

This PR allows supplying default tags in WriteOptions so that it can carry all write API configuration options.
* add `defaultTags` into WriteOptions
* use then in WriteApiImpl when set
* tests default tags in WriteOptions

feat(write): allow to supply default tags in WriteOptions

---

CHANGELOG.md
examples/write.js

Write example is enhanced to explain the significance of the precision argument during WriteApi construction, to prevent  confusions as in #206

chore: update write example with precision docs

---

CHANGELOG.md
packages/core/src/util/escape.ts
packages/core/test/fixture/escapeTables.json

Related to https://github.com/influxdata/influxdb-client-java/issues/127

fix: serialization of `\n`, `\r` and `\t` to Line Protocol

---

CHANGELOG.md
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/browser/emulateBrowser.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

Closes #208
- use InfluxDB1.8 error message from X-Influxdb-Error HTTP header when no message body is sent
- both node and browser transports changed

fix(core/transport): fall back to 1.8 X-Influxdb-Error HTTP header when no error body is available

---

package.json

This PR repair the main typedoc task than now fails in a cleaned repo. The api package typedoc requires a build of the core module.
BuildD the code module before running typedoc on apis

chore(docs): repair main typedoc script

---

CHANGELOG.md
packages/apis/generator/generateApi.ts
packages/apis/src/generated/DashboardsAPI.ts
packages/apis/src/generated/PackagesAPI.ts
packages/apis/src/generated/TasksAPI.ts

This PR adds default documentation of a body property in generated APIs. See #211

docs: add default documentation to body property in generated APIs

---

CHANGELOG.md
packages/core/src/errors.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/retryStrategy.ts
packages/core/test/unit/impl/retryStrategy.test.ts
packages/core/test/unit/query/flux.test.ts

This PR improves
- retry strategy (internal) to count with the number of already failed attempts + add a better test for exponential backoff
- improve test for flux sanitized strings

chore(core): improve retry strategy and tests

---

CHANGELOG.md
packages/core/src/query/FluxTableMetaData.ts
packages/core/test/unit/QueryApi.test.ts
packages/core/test/unit/query/FluxTableMetaData.test.ts

Closes #227
`tableMeta.toObject(row)` in this PR newly returns object with `null` numbers if an associated row value is empty.  
. Before this PR, it contained 0 in columns with empty double values and an empty string for long and unsignedLong values. 
This PR changes the return value of `tableMeta.toObject(row)`, which now returns a different object. This returned object is not documented. If there would be complications with this chage, the following extra code can be added to take back the previous behavior:
```
import { typeSerializers } from '@influxdata/influxdb-client'
typeSerializers.double = (val) => +val
typeSerializers.long = (val) => val
typeSerializers.unsignedLong = (val) => val
```

fix(core): change default number serializes to return null to represent emptiness

---

CHANGELOG.md
README.md
examples/README.md
examples/writeAdvanced.js
packages/core/src/InfluxDB.ts
packages/core/src/WriteApi.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/query/FluxTableMetaData.test.ts
scripts/enhance-doc-index-md.js

This PR adds self-explaining writeAdvanced.js example that shows and demonstrates advanced write options + adds a couple of fixes and corrections that makes the example better to understand + improves tests.

docs(examples): add writeAdvanced.js example

---

package.json
packages/apis/package.json
packages/core/package.json
yarn.lock

This PR removes `typedoc` and associated scripts from package.json files. It is no longer used, API documentation is generated in the project root by running `yarn apidoc`.
Additionally, it upgrades all package.json dependencies.

chore: remove typedoc

---

CHANGELOG.md
README.md
package.json
packages/core/package.json
packages/core/src/InfluxDB.ts
packages/core/src/impl/QueryApiImpl.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/query/FluxTableColumn.ts
packages/core/src/query/FluxTableMetaData.ts
packages/core/test/unit/Influxdb.test.ts
packages/core/test/unit/Point.test.ts
packages/core/test/unit/QueryApi.test.ts
packages/core/test/unit/impl/browser/emulateBrowser.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts
yarn.lock

This PR contains the following maintenance changes:
- upgraded dependencies to the latest possible version
- upgrade NYC coverage to 15.1.0
- uses ts3.7 nullish coalescing where it was the case to use it

chore: upgrade dependencies

---

CHANGELOG.md
packages/core/src/impl/retryStrategy.ts
packages/core/src/options.ts
packages/core/test/unit/impl/retryStrategy.test.ts
scripts/enhance-doc-index-md.js

This PR changes the **default** retry strategy options:
- initial/minimum retry delay is **5** seconds
- max retry delay is **180** seconds
- at most **3** retries 
- the base for the exponential backoff is set to **5** seconds, the default retry delays are now [5, 25, 125] seconds + jitter.

feat(core): Unify default retry strategy settings across all InfluxDB v2 clients

---

packages/apis/package.json
packages/core/package.json
yarn.lock

This PR
- upgrades the rollup terser plugin (used only during build) in order to fix security issue https://github.com/advisories/GHSA-hxcc-f52p-wc94.
- upgrades the rollup typescript2 plugin to a version that does not clash with other plugins
- upgrades rollup to the latest version

chore: upgrade rollup and plugins

---

CHANGELOG.md
packages/core/src/impl/ChunksToLines.ts
packages/core/test/fixture/chunksToLinesTables.json

Fixes #236
The transformation that creates query result lines out of HTTP response chunks did not properly detect quoting that could possibly ignore newline characters. If a first chunk ends with an open quote, the next chunks did not remember that the quote was opened in the previous chunk and then ignores newline characters. This is fixed in this PR, the opened quote is remembered as a state variable of the transformation.

fix(core/query): repair wrong quote detection in  chunks to lines transformation

---

CHANGELOG.md
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

This PR changes the client's node transport to also include url's context path to every request:
```js
#!/usr/bin/env node
...
const influxDB = new InfluxDB({url:'http://my-proxy:1234/influx', token})
...
const writeApi = influxDB.getWriteApi(org, bucket, 'ns')
...
// every API call now includes url's path, the following API call 
// will do POST http://my-proxy:1234/influx/api/v2/write
//
// before this PR: POST http://my-proxy:1234/api/v2/write
writeApi.writePoint(point1)
```
The context path is already respected in the browser (fetch) transport.

feat(core): keep url's context path in node transport

---

CHANGELOG.md
packages/core/src/query/FluxTableColumn.ts
packages/core/src/query/FluxTableMetaData.ts
packages/core/src/query/index.ts
packages/core/test/unit/query/FluxTableMetaData.test.ts

Fixes #239 and introduce functions that let users choose how to de-serialize `dateTime:RFC3339` type.

feat(core): add helpers to let users choose how to deserialize dateTime:RFC3339 query response data type

---

examples/env.js

Fixes #243 
Example environment variables renamed for the sake of consistency with InfluxDB v2 tools. `INFLUXDB_* is now INFLUX_*`

chore(examples): rename env vars

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #245
Throw error when writing to a closed WringApi.

fix(core): throw exception when using closed writeApi

---

CHANGELOG.md
packages/core/src/QueryApi.ts
packages/core/src/impl/QueryApiImpl.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/integration/rxjs/QueryApi.test.ts
packages/core/test/unit/QueryApi.test.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/browser/emulateBrowser.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

This PR adds the following method to QueryApi:
```
/**
* QueryRaw executes a query and returns the full response as a string.
* Use with caution, a possibly huge stream is copied to memory.
*
* @param query - query
* @returns Promise of response text
*/
queryRaw(query: string | ParameterizedQuery): Promise<string>
```
The new method is suitable in cases that require the whole flux CSV response. It fits well with the examples provided in https://github.com/influxdata/giraffe
Additionally
+ wrong usage of expect.fail was fixed in all tests
+ transport implementations were changed to prefer the requested content type, if possible

feat(core/query): allow to receive the whole query response as text

---

CHANGELOG.md
packages/core/src/query/flux.ts
packages/core/test/unit/query/flux.test.ts

Fixes #251
This PR fixes the `flux` template function so that 
- a non-interpolated (simple) string returns a flux expression
- an empty flux expression can be wrapped into another flux expression
It also improves and repairs the tests of the flux template function, some of them were not executed due to incorrect usage of mocha.

fix(core): repair nesting of flux expressions

---

packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

transport.request must also return text when application/csv content type is received

fix(core/transport): return text data also for application/csv content type

---

CHANGELOG.md
packages/core/src/impl/linesToTables.ts
packages/core/src/query/FluxTableColumn.ts
packages/core/src/query/FluxTableMetaData.ts
packages/core/src/query/index.ts
packages/core/test/integration/rxjs/QueryApi.test.ts
packages/core/test/unit/query/FluxTableMetaData.test.ts

This PR changes FluxTableColumn and FluxTableMetaData classes to interfaces. This change better reflects what the library users should care (i.e. shape of the object passed, not the instance) and also allows for better tree shaking (influxdata/giraffe#282 will completely tree shake the whole @influxdata/influxdb-client package, it would not without this change). 
This change should not cause major compatibility issues, because:
- the new interfaces have the same shape as the previous classes
- it is not expected that users will create new FluxTableColumn or FluxTableMetaData instances or use `instanceof` checks against such classes. In the rare case they already do, there are new exported functions: createFluxTableColumn, createFluxTableMetaDta that replace constructor.
- all existing …

feat(core): convert FluxTableColumn and FluxTableMetaData to interface

---

CHANGELOG.md
packages/core/src/impl/ChunksToLines.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/test/unit/impl/ChunksToLines.test.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts

This PR fixes
- browser (fetch) transport: do not throw any error after the user programmatically cancels result processing
- browser (fetch) transport: use [abortable fetch](https://developers.google.com/web/updates/2017/09/abortable-fetch) to also abort HTTP processing if the user programmatically cancels query result processing
- browser (fetch) transport: query processing is always completed after the user programmatically cancels result processing
- i.e. the same as in NodeHttpTransport
- chunk to CSV lines conversion: do not emit new lines after the user programmatically cancels processing of a query

fix(core): finish query when cancelled by the user

---

.circleci/config.yml
CHANGELOG.md
examples/README.md
examples/createBucket.js
examples/env.js
package.json
packages/apis/src/index.ts
packages/core/src/index.ts
packages/core/test/integration/rxjs/QueryApi.test.ts
packages/core/test/unit/Influxdb.test.ts
packages/core/test/unit/QueryApi.test.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

Fixes #247 
Default InfluxDB port changed from 9999 to 8086 in examples, code comments and (for the sake of completeness) tests.
\+ check examples for eslint errors during CI tests

feat: change default InfluxDB port to 8086

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/completeCommunicationObserver.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/transport.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

Fixes #263 
1. A warning is printed to console on an attempt to configure the client with `url` having `/api/v2` suffix:
`Please remove '/api/v2' context path from InfluxDB base url, using http://test:8096 !`
2. WriteAPI requires status code 204 in HTTP POST response
3. Transport layer was changed (in a backward-compatible way) to also report the response status code.

fix(core): require status code 204 in write response

---

CHANGELOG.md
packages/core/src/QueryApi.ts
packages/core/src/WriteApi.ts
packages/core/src/impl/QueryApiImpl.ts
packages/core/test/unit/QueryApi.test.ts

The `QueryApi.with` function now returns a new QueryApi function. Making the QueryApi immutable is rather an idiomatic change. Immutability clarifies the API and avoids unwanted side-effects. This impact on existing usage is hard to imagine.

chore(core): make QueryApi instance immutable

---

.circleci/deploy-nightly-version.sh
CHANGELOG.md
README.md
package.json
packages/apis/rollup.config.js
packages/apis/src/APIBase.ts
packages/core-browser/.npmignore
packages/core-browser/README.md
packages/core-browser/package.json
packages/core/README.md
yarn.lock

This PR adds a new `@influxdata/influxdb-client-browser` module to let users use ESM distribution that works in a browser environment (window / worker) when bundling their app (using parcel, rollup, webpack, ...). The README.md files in core and core-browser packages were enhanced to provide more details.
@influxdata/influxdb-client has not changed, it still contains all 6 types of distributions with 3 of them provided via `package.json`:
- ([main](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/package.json#L22)) CJS for node.js
- ([module](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/package.json#L23)) ESM for node.js
- ([browser](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/package.json#L24)) UMD for …

feat: introduce @influxdata/influxdb-client-browser module

---

.circleci/deploy-nightly-version.sh

- uses `$CIRCLE_BUILD_NUM` for 'indexing' of nightly build. 
The Lerna uses number of commit from latest tag to retrieve 'index' of canary build. This doesn't work if we have initial deploy from local machine and then deploy from CI (both have same index).

fix: deploying nightly packages

---

CHANGELOG.md
package.json
packages/core/src/impl/browser/FetchTransport.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts

Fixes #262
- Opera and Chrome do not allow to control User-Agent header
- Firefox and Safari do, but it fails in the cloud anyway
Therefore this PR proposes to skip the setting of a custom User-Agent header when used in the browser. A custom User-Agent header is set only when used from node.js.
\+ changed the main `yarn test` to work also when examples are installed

fix(core): don't set User-Agent header in browser

---

CHANGELOG.md
packages/core/src/impl/browser/FetchTransport.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts

This PR optimizes UTF-8 encoding in the browser by using TextEncoder API.

feat(core): optimize UTF-8 encoding

---

packages/core-browser/package.json

This PR ensures that lerna will deploy `core-browser` package upon change in the `core` package.

chore(core-browser): depend on core

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/RetryBuffer.test.ts
packages/core/test/unit/util/waitForCondition.ts

This PR allows being notified about the success of the write operation when `writeSuccess` is supplied during the creation of WriteApi. Additionally, the existing WriteApi tests are improved to wait for success or failure (instead of waiting 20ms), the tests thus become more robust (they started to fail seldomly in CI).

feat(core): allow to notify about write success

---

CHANGELOG.md
packages/core/src/InfluxDB.ts
packages/core/src/QueryApi.ts
packages/core/src/impl/QueryApiImpl.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/QueryApi.test.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #282
This PR allows specifying custom HTTP headers in an API instance returned by `InfluxDB.getQueryApi` or `InfluxDB.getWriteApi` via the existing `options` parameter.
Examples:
```js
const org = 'my-org'
const influxDB = new InfluxDB({url: 'http://localhost:8086', token: 'abcd'})
// the returned API instances are authorized with `myToken` in place of default `abcd`
const writeApi = influxDB.getWriteApi(org, bucket, precision, {headers: {authorization: `Token myToken`}})
const queryApi = influxDB.getQueryApi({org, headers: {authorization: `Token myToken`}})
```

feat(core): allow to specify custom HTTP headers in WriteApi or QueryApi

---

packages/core/src/errors.ts
packages/core/test/unit/errors.test.ts

This PR adds tests to check that the custom errors conform to the Error standard.

chore(core): add tests for custom errors

---

CHANGELOG.md
packages/core/src/errors.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

Fixes #285
If InfluxDB error response contains JSON with code and message, the client throws an HttpError with code and message properties taken from the response. Additionally, the thrown error contains `json` property with a parsed error response.

feat(core): throw HttpError with code and message from response body

---

CHANGELOG.md
packages/core/src/InfluxDB.ts
packages/core/src/options.ts
packages/core/test/unit/Influxdb.test.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #290
The core module exports WritePrecision, which is a [const enum](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums) that is inlined during package build. Typescript code that imports this client fails during compilation because of this enum when  `--isolatedModules` flag is used. 
Since WritePrecision is not used directly in exported APIs (but WritePrecisionType is), it can be removed. WritePrecisionType already properly describes the shape of the expected value type (including also the shape of the removed WritePrecision const enum).
This PR introduces a breaking change. In an unlikely event of using a removed WritePrecision, a typescript code has to be changed to use the precision constant directly (`'ns'` in place of …

fix(core): remove WritePrecision enum

---

CHANGELOG.md
examples/.eslintrc.json
examples/README.md
examples/query.deno.ts

This PR adds a query example that shows how [deno](https://deno.land) is supported.

feat(deno): add deno query example

---

.circleci/config.yml

This PR ignores `gh-pages` branch in tests ad coverage executions with the help of https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md#filters

chore(ci): ignore gh-pages branch in CI workflows

---

CHANGELOG.md
examples/sessionAuth.js
examples/tokens.js
packages/apis/src/APIBase.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/results/CommunicationObserver.ts
packages/core/src/transport.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

This PR 
- allows receiving HTTP response headers in all APIs
- allows authenticating users with username+password in all APIs
- adds `tokens.js` example that shows how to use username+password authentication to establish authenticated session to manage authorization tokens

feat: expose response headers, username+password authentication

---

CHANGELOG.md
packages/core/src/impl/node/NodeHttpTransport.ts

Z_SYNC_FLUSH constant was moved from zlib to zlib.constants sync node v7.0 , so the code in this PR.

chore(core): remove deprecated zlib constants

---

CHANGELOG.md
packages/apis/package.json
packages/core/package.json
packages/giraffe/api-extractor.json
packages/giraffe/package.json
scripts/enhance-doc-index-md.js
yarn.lock

Fixes #310
- upgrade @microsoft/api-extractor 
- upgrade @microsoft/api-documenter
- skipLibCheck for giraffe api-extractor is not required in the upgraded version of api-extractor

chore: upgrade api-extractor and api-documenter

---

CHANGELOG.md
examples/query.ts

This PR adds an example that shows how to query the whole result.

feat(examples): add queryRaw example

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/options.ts
packages/core/src/transport.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/browser/emulateBrowser.ts
packages/core/tsconfig.json

Fixes #325
* WriteApi now gzips write requests when they are greater than 1000 bytes
* Developers can customize the threshold that applies gzip compression in `WriteOptions`
```
/** When specified, write bodies larger than the threshold are gzipped  */
gzipThreshold?: number
```
* `gzipThreshold` was also added in `SendOptions` of the transport layer
* node.js transport implementation applies gzip threshold
* the browser implements currently does not gzip at all
* doing so would either triple the binary size of the client, or require an external dependency on gzip implementation
* the browser transport can be customized to do gzip, an example provided with pako.js

feat(core/write): apply gzip compression to writes with body length > 1000

---

CHANGELOG.md
packages/core/src/Point.ts
packages/core/src/util/currentTime.ts
packages/core/test/unit/Point.test.ts

feat(core): use nanosecond precision by default in Point.toLineProtocol() 

---

CHANGELOG.md
packages/core/src/Point.ts
packages/core/test/fixture/pointTables.json
packages/core/test/unit/Point.test.ts

This PR Adds uintField fn to Point class so that it simplifies adding of unsigned integer fields to a protocol line. Added js numbers must be >=0 and <Number.MAX_SAFE_INTEGER. Other values (including a possible bigint) are converted to string and checked that they contain just numbers and that the string is less than 2^64 (18446744073709551616)

feat(core): add uintField fn to Point

---

CHANGELOG.md
packages/core/src/impl/RetryBuffer.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/retryStrategy.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/RetryBuffer.test.ts
packages/core/test/unit/impl/retryStrategy.test.ts

This PR aligns retry strategy implementations across all official InfluxDB client libraries so that a delay for the next retry delay is a random value in the interval `minRetryInterval * exponentialBase^(attempts)` and `minRetryInterval * exponentialBase^(attempts+1)` increased by a random(jitter).
The defaults were changed to `minRetryInterval=5_000, exponentialBase=2, maxRetryDelay=125_000, maxRetries=5`
Retry delays are by default randomly distributed within the ranges of [5_000-10_000, 10_000-20_000, 20_000-40_000, 40_000-80_000, 80_000-125_000] + random(200). When an overall time spent by retrying exceeds a configurable `maxRetryTime` (180_000 millis by default), the write is not retried and fails.

feat(core): use exponential random retry strategy

---

CHANGELOG.md
packages/core/package.json
packages/core/src/impl/ObservableQuery.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/observable/types.ts
packages/core/test/integration/rxjs/QueryApi.test.ts
packages/core/test/unit/Influxdb.test.ts
packages/giraffe/package.json
yarn.lock

The typings used around ObservableQuery are not compatible with rxjs7. This fixes that so they are now compatible with rxjs 6 & 7. Also the tests now use rxjs7

fix(core): rxjs7 compat

---

CHANGELOG.md
packages/core/src/results/FluxTableMetaData.ts
packages/core/test/unit/results/FluxTableMetaData.test.ts

Related to https://github.com/influxdata/influxdb-client-java/issues/239
Fixed parsing `Inf+` for [histogram() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/histogram/).
```csv
#group,false,false,true,true,true,true,true,true,true,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,string,string,double,double
#default,_result,,,,,,,,,,,
,result,table,_start,_stop,_field,_measurement,language,license,name,owner,le,_value
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT License,influxdb-client-csharp,influxdata,0,0
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT …
```

fix: parsing infinite numbers

---

CHANGELOG.md
package.json
packages/apis/package.json
packages/core/package.json
packages/giraffe/package.json
yarn.lock

Fixes #350
`api-documenter` and `api-extractor` was also upgraded as they suggested to upgrade to support 4.3.5

chore: upgrade to typescript 4.3.5

---

CHANGELOG.md
examples/README.md
examples/follow-redirects.js
examples/package.json
packages/core/package.json
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/options.ts
packages/core/test/unit/Influxdb.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts
yarn.lock

This PR allows configuring the client to use 'follow-redirects' node.js library in order to follow redirects in communication with InfluxDB. Tests, docs, and an example are included.

feat(core): allow following HTTP redirects in node.js

---

packages/core/src/options.ts

This PR improves documentation of transportOptions, it is now explained 
- what options can be specified under the hood
- how to programmatically turn off certification verification in node.js
Related to #367

chore(core): improve documentation of transport options

---

CHANGELOG.md
packages/core/src/Point.ts
packages/core/test/fixture/pointTables.json
packages/core/test/unit/Point.test.ts
yarn.lock

Fixes #369
Point's intField/uintField/floatField newly throws when out-of-range or NaN value is supplied.

fix(core): throw error when int/uint/float point field is out of range

---

CHANGELOG.md
packages/core/src/impl/RetryBuffer.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/util/logger.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/util/logger.test.ts

Fixes #381 , renames `Logger` variable to `Log` in order to avoid conflicts with `Logger` interface in the generated documentation.

chore(core): rename internal Logger to Log

---

CHANGELOG.md
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

Fixes #380 
This PR removed undefined fields from node request options to avoid node.js validation errors.

fix(core): remove undefined fields from request options

---

CHANGELOG.md
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

Fixes #385 . The root cause is that InfluxDB server responds with "application/json" content type, 204 HTTP status and an empty body. An empty body then cannot parsed as JSON.
When an empty body with an `application/json` content type recived, `undefined` is returned as a response body.

fix(core): do not parse empty JSON response

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/test/unit/WriteApi.test.ts

Fixes #391 -  avoid double-escaping of default tags

fix(core): repair double-escaping of default tags

---

CHANGELOG.md
README.md
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/options.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts

This PR allows to set up HTTP proxy using a `proxyUrl` property in InfluxDB configuration object, without the need [to use an extra 3rd party agent](https://github.com/influxdata/influxdb-client-js/issues/319#issuecomment-808154245). Moreover, custom headers for all requests can be also set using the `headers` property in the InfluxDB configuration, this functionality can be used to set up proxy authorization headers.
This feature makes sense only in the context of node.js. Browser code can't control proxy setting,  [deno](deno.land) setups HTTP proxy using env variables.

feat(core): node.js builtin-proxy

---

CHANGELOG.md
packages/core/src/impl/node/NodeHttpTransport.ts

Fixes #303
When GZIP compression is applied to a response, the node's client can effectively close the request before the last piped gunzip happens. This PR makes sure that the results are not closed when results are still available. The response is only completed (successful) if and only if all (possibly none) response data chunks are read.

fix(core): repair handling of gzipped responses

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/src/util/utf8Length.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/util/utf8Length.test.ts

This PR allows limiting write batches to have a maximum length in bytes (50M by default) using a new **maxBatchBytes** write option.

feat(core): limit write batch maximum size in bytes

---

packages/core/test/unit/WriteApi.test.ts

This PR enhances tests so that it makes sure that UnhandledPromiseRejection is not thrown even when a batch write is initialized by exceeding the max (bytes) size of batch.

chore(core): test failed write when maxBatchBytes is exceeded

---

CHANGELOG.md
packages/apis/generator/generateApi.ts
packages/apis/src/generated/MeAPI.ts
packages/apis/src/generated/SigninAPI.ts
packages/apis/src/generated/UsersAPI.ts

Fixes #410
This PR changes the generator and the generated API to make basic authentication optional, it is in fact.

fix(apis): make basic authentication optional

---

.circleci/config.yml
package.json
packages/giraffe/package.json
yarn.lock

Fixes #409
This PR downloads and runs the` codecov` binary to report code coverage.
Despite the recommendations, it cannot use [codecov orb](https://circleci.com/developer/orbs/orb/codecov/codecov), because it fails on:
```
codecov/codecov@3.2.2 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.
```
Using unknown orbs in advance for the whole `influxdata` organization is not a configuration option to go with.

chore(ci): use codecov binary

---

CHANGELOG.md
examples/query.ts
examples/rxjs-query.ts
packages/core/src/results/FluxTableColumn.ts
packages/core/src/results/FluxTableMetaData.ts
packages/core/test/unit/results/FluxTableMetaData.test.ts

This PR simplifies retrieval of particular row values so that
- there is no need to create a JS object to get selected (and possibly unknown) columns from results, it is simpler and more efficient to use tableMeta.get(row, column)
- a JS Proxy can be used to transform the row to an object with properties representing column names.
The existing `query.ts` is modified to show it.

feat(core/query): simplify retrieval of particular row values

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts

This PR
- improves documentation to address #420
- adds tests to verify write attempts
- adds `expires` parameter to `writeFailed` together with a test
- simplifies the implementation

feat(core): enhance writeFailed callback

---

examples/influxdb-1.8.ts
examples/query.ts
examples/queryWithParams.ts

While using the JS client in our firstMile work, I copied the code from the example and kept running into syntax errors. After I changed to the code to look the way this updated example looks, it started working properly.

docs: update query example

---

CHANGELOG.md
packages/core/test/unit/query/flux.test.ts

This PR adds tests for parameter escaping in a flux tagged template, given the feedback from #432.

chore(core): improve flux function tests

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts

This PR adds write consistency parameter that could be set when writing to InfluxDB Enteprise, as explained in https://docs.influxdata.com/enterprise_influxdb/v1.9/concepts/clustering/#write-consistency .

feat(core): allow to specify write consistency

---

package.json
packages/apis/package.json
packages/core-browser/package.json
packages/core/package.json
packages/giraffe/package.json

This PR changes the descriptions to reference InfluxDB `2.x` version. It was `2.1` before this PR.

chore: use 2.x version in descriptions

---

packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/util/waitForCondition.ts

This PR repairs a flickering test.

chore: repair flickering test

---

CHANGELOG.md
examples/invokableScripts.js
packages/apis/resources/cloud.yml
packages/apis/resources/invocable-scripts.yml
packages/apis/resources/operations.json
packages/apis/resources/oss.yml
packages/apis/src/generated/ConfigAPI.ts
packages/apis/src/generated/DashboardsAPI.ts
packages/apis/src/generated/DebugAPI.ts
packages/apis/src/generated/HealthAPI.ts
packages/apis/src/generated/MetricsAPI.ts
packages/apis/src/generated/PingAPI.ts
packages/apis/src/generated/WriteAPI.ts
packages/apis/src/generated/types.ts

Related to https://github.com/influxdata/openapi/pull/317
- regenerate APIs from swagger
- rename invocable scripts to invokable scripts

chore: rename InvocableScripts to InvokableScripts

---

.github/PULL_REQUEST_TEMPLATE
.github/semantic.yml
.github/workflows/semantic.yml

The github application "semantic-pull-requests" uses a very old node version and presents security vulnerabilities. The repo manager has not addressed the issue and has become nonresponsive. Influxdata has its own solution based in github reusable workflows.  
**This change is org-wide to address security vulnerabilites in semantic-pull-requests, by removing it.**
Closes #
Remove semantic-pull-requests.  Add https://github.com/influxdata/validate-semantic-github-messages
'nuff said
- [n/a] CHANGELOG.md updated
- [n/a] Rebased/mergeable
- [n/a] A test has been added if appropriate
- [n/a] Tests pass
- [yes] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [n/a] Sign …

refactor: Deprecate and remove semantic-pull-requests, insert influxdata replacement reusable workflow solution.

---

CHANGELOG.md
packages/core/src/impl/browser/FetchTransport.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts

Fixes #446 . Custom transport options are herein also accepted in a browser environment. 
For example: to change the [credentials](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials) option from a default `omit` to `include` :
```js
new InfluxDB({
url,
token,
transportOptions: {credentials: 'include'},
})
```

feat(core): allow custom transport options in a browser

---

CHANGELOG.md
packages/core/src/WriteApi.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/test/unit/WriteApi.test.ts

This PR allows changing the default HTTP path of InfluxDB write API service so that any endpoint that accepts InfluxDB line protocol data can be used:
```
const writeAPI = new InfluxDB({url, token}).getWriteApi(org, bucket, precision)
writeAPI.httpPath = '/api/v1/influxdb/write'
```

feat(core): allow to overwrite default write API HTTP path

---

examples/package.json
package.json

This PR removes `name` and `version` from private package.json files, so they could not be used in any possible Dependency Confusion or supply chain substitution attacks.

chore: remove name and version from private packages

---

CHANGELOG.md
examples/writeAdvanced.js
packages/core/src/QueryApi.ts
packages/core/src/results/AnnotatedCSVResponse.ts

This PR adds TCP connection reuse to writeAdvanced example. It also contains a few doc improvements.

chore(examples): reuse TCP connections in writeAdvanced example

---

CHANGELOG.md
packages/apis/package.json
packages/core-browser/package.json
packages/core/package.json
packages/giraffe/package.json

Fixes #459
Pointers to type definitions are added to `package.json`'s `exports` section as explained in https://www.typescriptlang.org/docs/handbook/esm-node.html .

feat: add type definitions for typescript 4.7+

---

CHANGELOG.md
package.json
yarn.lock

Fixes https://github.com/influxdata/influxdb-client-js/security/dependabot/41
This PR upgrades lerna to v5

chore: upgrade lerna to v5

---

CHANGELOG.md
packages/core/src/query/flux.ts
packages/core/test/unit/query/flux.test.ts

Fixes #467
Sanitizing of JS values to flux values is revised herein. 
This PR fixes sanitizing of flux values so that
- a float value is represented as [a flux float literal](https://docs.influxdata.com/flux/v0.x/data-types/basic/float/#float-syntax) if possible or as `float(v: "${value}")` if it is not
- an integer value must strictly match https://docs.influxdata.com/flux/v0.x/data-types/basic/int/
- a regexp value is represented as [a regexp literal](https://docs.influxdata.com/flux/v0.x/data-types/basic/regexp/#regular-expression-syntax)
- documentation improved with a pointer to flux documentation of regexp

fix(core): repair sanitizing of numbers and regular expressions

---

CHANGELOG.md
packages/core/src/query/flux.ts
packages/core/test/unit/query/flux.test.ts

This PR adds support for `bigint` values to flux tagged template. Bigint is properly supported in `fluxInteger`, `toFluxValue` and `fluxFloat` flux converters.

feat(core): support bigint in flux tagged template

---

packages/apis/package.json
packages/core-browser/package.json
packages/core/package.json
packages/giraffe/package.json
packages/giraffe/rollup.config.js

This PR repairs `@influxdata/influxdb-client-giraffe` build to produce browser code. 
#473 introduces the newest version of `@rollup/plugin-node-resolve` that prefers `package.json`'s `exports` field to determine the file to use. The old configuration did not work anymore and resulted in importing a node.js bundle with wrong dependencies on node packages.
- giraffe package: rollup resolve config was changed to use `browser: true`
- package.json of 'core', 'apis', 'core-browser' packages was changed so that `exports/browser` is before `exports/import`, which is required for rollup to pickup browser distribution properly ... the order of exports matters, 'import' is always chosen by rollup when found before 'browser' ... which is the root caused that caused the problems
- any rollup warning …

fix(giraffe): repair build to rely upon rollup browser support

---

packages/apis/generator/logger.ts

This PR fix error during `yarn test`:
```
generator/logger.ts:1:9 - error TS2614: Module '"chalk"' has no exported member 'yellow'. Did you mean to use 'import yellow from "chalk"' instead?
1 import {yellow} from 'chalk'
~~~~~~
Found 1 error in generator/logger.ts:1
```

fix: `Module '"chalk"' has no exported member 'yellow'`

---

packages/apis/package.json

This PR adds typescript checking to `test:ci` target of `api` package. 
Previously https://github.com/influxdata/influxdb-client-js/pull/474 passed, but it introduced a type error that was not triggered by circle CI within the PR, the overall tests should fail. They will fail after this PR.

fix(ci): add typescript check to test:ci target of api package

---

packages/apis/generator/logger.ts
packages/apis/package.json
yarn.lock

This PR removes chalk from client dev dependencies, it uses simpler code instead. The dependency was removed because it caused collisions during dependabot updates (#508 and #502).

chore: remove direct dependency on chalk

---

packages/core/package.json
packages/giraffe/package.json
yarn.lock

This PR takes back `ts-node/register` when running code coverage, nyc (also c8 coverage tools) does not report correct coverage data with `esbuild-runner/register`. I found no working solution to keep the fast esbuild processing together with a working code coverage.

fix(core): repair coverage that doesn't work with esbuild-runner

---

CHANGELOG.md
packages/core/src/impl/RetryBuffer.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/options.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/RetryBuffer.test.ts

This PR improves write retry buffer so that
- the calling code be informed about items that were removed in order to keep the size of the retry buffer under the configured limit (32_000 lines, maxBufferLines options) using a new optional `writeRetrySkipped` callback
- when the buffer becomes full, the oldest items (according to the time of the first failures) are always removed, previously oldest items according to the time they were added/re-added to the retry buffer were removed; the new strategy in this PR is fair
- the code now remembers scheduled retry time for each failed write, it always follows the order of retry execution regarding the scheduled retry time

feat(core): improve write retry buffer

---

yarn.lock

This reverts commit e07173538ffc9571f31c7d73ebe2a2f940ad1e14, it fails in CI

chore(deps-dev): revert @microsoft/api-extractor to 7.29.3

---

CHANGELOG.md
package.json
packages/apis/package.json
packages/core/package.json
packages/giraffe/package.json
scripts/fix-extracted-api-files.js
yarn.lock

Fixes #566
- reference identifiers in `api-extractor` output are validated against existing identifiers, `fix-extracted-api-files.js` was modified
- references to unknown identifiers are fixed automatically, if possible
- usually a replacement of `!~` to simple `!` is sufficient to make things work, for example `FIXED @influxdata/influxdb-client!~WriteRetryOptions:interface => @influxdata/influxdb-client!WriteRetryOptions:interface`
- there is also a map that fixes a few namings errors produced by `api-extractor` and a list of id prefixes that are ignored (with a documented explanation)
- all the fixes are printed to console
- failure to resolve a documentation reference is reported with `1` exit code
- all errors are printed together before the process exits
- `yarn apidoc:ci` will fail …

fix(docs): repair generated API documentation so that links between packages are rendered

---

CHANGELOG.md
packages/core/src/results/CommunicationObserver.ts
scripts/fix-extracted-api-files.js

This PR renames the client's `Headers` type to `HttpHeaders` in order to avoid clashing with a built-in DOM Headers type. `HttpHeaders` are also exported as `Headers`, so there is no backward-compatibility introduced herein.
This change also fixes the model of the generated API documentation (created by api-extractor), the client's HttpHeaders now has a unique canonical name that is referenceable.

fix(docs): rename Headers to HttpHeaders to avoid clash with DOM's Headers type

---

Makefile
scripts/change-version.js

Fixes #568
Simple node script is used to do the same job that `sed` was intended to do, the code is now independent on platform (Unix, Mac).

fix: use node script in place of sed #568

---

CHANGELOG.md
packages/core/src/results/FluxTableColumn.ts
packages/core/test/unit/results/FluxTableMetaData.test.ts

Fixes #578
Empty boolean value in a flux csv response is herein by default serialized to `null`, i.e. the same way as other types are.

fix(core): repair deserialization of empty string to boolean

---

CHANGELOG.md
README.md
examples/README.md
examples/ping.mjs
packages/apis/DEVELOPMENT.md
packages/apis/README.md

This PR repairs doc links to point to the **latest** API docs, it was 2.1 before this PR. It is herein changed to `2.x` in texts and `latest` in URLs.

chore(docs): repair doc links to point to latest API docs

---

CHANGELOG.md
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/completeCommunicationObserver.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/src/results/CommunicationObserver.ts
packages/core/src/results/FluxResultObserver.ts
packages/core/src/results/chunksToLines.ts
packages/core/src/results/linesToTables.ts
packages/core/test/unit/impl/browser/FetchTransport.test.ts
packages/core/test/unit/impl/browser/emulateBrowser.ts
packages/core/test/unit/impl/node/NodeHttpTransport.test.ts
packages/core/test/unit/results/chunksToLines.test.ts
packages/core/test/unit/results/linesToTables.test.ts
packages/core/test/unit/util/waitForCondition.ts

This PR allows pausing query results by returning `false` in the `next` callback of `queryApi.queryLines` and `queryApi.queryRows` consumer. The consumer must define `useResume` callback that receives a function that resumes receiving data when called. This feature adds a low-level (node.js stream) style of lossless backpressure to query result processing via communication observer.
Method signatures changed, the `next` callback of `CommunicationObserver` and `FluxResultObserver` can newly return also a boolean value, `false` value will stop processing. All these changes are backward compatible, no change is required for the existing code.

feat(core): allow to pause/resume query result observers

---

CHANGELOG.md
packages/core/src/impl/RetryBuffer.ts
packages/core/test/unit/WriteApi.test.ts
packages/core/test/unit/impl/RetryBuffer.test.ts
packages/core/test/util.ts

Fixes #593
- write API and write retry tests were enhanced to check for unhandled promise rejections, because the unit test framework (mocha) silently swallows promise rejections. Unhandled promise rejections normally terminate node.js process (unless '
- retry buffer was fixed to silently consume write failures before re-scheduling it, it was this way correctly in 1.29 and changed in 1.30 in #547, the following lines were causing it: in https://github.com/influxdata/influxdb-client-js/pull/547/files#diff-16970e3a239345f536ebc0fa851bf7d9732aa1f22160fe5667a9e1bf7de42a52L100-L108

fix(core): fix unhandled promise rejection in write retry

---

.circleci/config.yml
CHANGELOG.md
README.md
examples/README.md

Fixes #623 
The Node v18 is new LTS version. For more info https://github.com/nodejs/Release#release-schedule.
1. Upgraded recommended node version to 18 (LTS)
2. Test client on actual maintained version of nodejs - `14`, `16`, `18`
https://github.com/nodejs/Release#release-schedule

chore(ci): upgrade recommended node version to 18

---

packages/core/src/InfluxDB.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/Influxdb.test.ts
packages/core/test/unit/QueryApi.test.ts

An `InfluxDB` object leaks the token given to it, in `InfluxDB._options`. Additionally, if no transport is provided, the generated `TransportImpl` object also leaks the token given to it, in `TransportImpl.token`.
The proposed changes fix this issue by deleting the token from `InfluxDB._options` once it is passed to `TransportImpl`, and making the token property in `TransportImpl` a JavasScript private class property.
Note: because the token is deleted from `InfluxDB._options`, the unit test `'is created from configuration with url and token'` was modified to so that it passes, by deleting the `token` property from the reference the actual value `InfluxDB._options` is compared to. The test was not deleted to minimize the PR changes, but in its current form may be redundant.

fix: do not leak token in client and transport objects

---

CHANGELOG.md
packages/core/src/errors.ts
packages/core/src/impl/WriteApiImpl.ts
packages/core/src/impl/browser/FetchTransport.ts
packages/core/src/impl/node/NodeHttpTransport.ts
packages/core/test/unit/errors.test.ts

Fixes  https://github.com/influxdata/influxdb-client-js/issues/1018
Adds headers to the HTTP error response.

feat: add headers to http error responses

---

CHANGELOG.md
examples/README.md
examples/httpErrorHandled.mjs
examples/package.json
packages/core/test/unit/WriteApi.test.ts

- Add an example of using recently added `HttpError` type
- Add an extra integration test working with this type

docs: adds httpErrorHandled example and integration test for HttpError

---

CHANGELOG.md
packages/core/src/impl/WriteApiImpl.ts

InfluxDB v3 returns 201 for partial write errors.
Helps internal issue https://github.com/influxdata/idpe/issues/18710

fix: handle 201 response from write endpoint
